name: Compile Windows binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.108
       
    - name: Restore dependencies
      run: dotnet restore -r win-x64 --configfile GalaxyBudsClient/nuget.config
    - name: Build x64
      run: dotnet publish -r win-x64 -o bin_win64 -c Release -p:PublishTrimmed=true -p:PublishSingleFile=true --self-contained true --no-restore GalaxyBudsClient/GalaxyBudsClient.csproj
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GalaxyBudsClient_win64_portable
        path: bin_win64/GalaxyBudsClient.exe
    
  build-x86:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.108
       
    - name: Restore dependencies
      run: dotnet restore -r win-x86 --configfile GalaxyBudsClient/nuget.config
    - name: Build x86
      run: dotnet publish -r win-x86 -o bin_win32 -c Release -p:PublishTrimmed=true -p:PublishSingleFile=true --self-contained true --no-restore GalaxyBudsClient/GalaxyBudsClient.csproj
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GalaxyBudsClient_win32_portable
        path: bin_win32/GalaxyBudsClient.exe

  make-nsis-installer:
    runs-on: windows-latest
    needs: [build-x64, build-x86]
        
    steps:
    - uses: actions/checkout@v2
    - name: Prepare version information (1/3)
      uses: oprypin/find-latest-tag@v1
      with:
        repository: ThePBone/GalaxyBudsClient
        releases-only: true
      id: last_release  
    - name: Prepare version information (2/3)
      uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6
    - name: Prepare version information (3/3)
      run: echo '::set-output name=version::${{steps.last_release.outputs.tag}}-${{steps.short-sha.outputs.sha}}'
      id: version
      
    # Make x64 installer
    - name: Download artifact (x64)
      uses: actions/download-artifact@v2
      with:
        name: GalaxyBudsClient_win64_portable
        path: Galaxy Buds Client.exe
        
    - name: Create nsis installer (x64)
      uses: joncloud/makensis-action@v3.3
      with:
        script-file: "install.nsi"
        arguments: "-DPRODUCT_VERSION=\"${{steps.version.outputs.version}}\" -DPRODUCT_ARCH=\"64bit\""

    - name: Upload artifact (x64)
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GalaxyBudsClient_Setup_64bit_${{steps.version.outputs.version}}.exe
        path: GalaxyBudsClient_Setup_64bit_${{steps.version.outputs.version}}.exe

    # Make x86 installer
    - name: Download artifact (x86)
      uses: actions/download-artifact@v2
      with:
        name: GalaxyBudsClient_win32_portable
        path: Galaxy Buds Client.exe

    - name: Create nsis installer (x86)
      uses: joncloud/makensis-action@v3.3
      with:
        script-file: "install.nsi"
        arguments: "-DPRODUCT_VERSION=\"${{steps.version.outputs.version}}\" -DPRODUCT_ARCH=\"32bit\""

    - name: Upload artifact (x86)
      uses: actions/upload-artifact@v2.2.2
      with:
        name: GalaxyBudsClient_Setup_32bit_${{steps.version.outputs.version}}.exe
        path: GalaxyBudsClient_Setup_32bit_${{steps.version.outputs.version}}.exe

