name: Validate translations

on: [push]

jobs:
  generate-translation-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Run XAML validator
        uses: ThePBone/XamlTranslationValidator@v1.2
        with:
          source-xaml: 'GalaxyBudsClient/i18n/en.xaml'
          translation-xaml: 'GalaxyBudsClient/i18n/*.xaml'
          output-directory: 'meta/'
          output-name-summary: 'translations.md'
          custom-note: 'Translation instructions are available [in the wiki](https://github.com/ThePBone/GalaxyBudsClient/wiki/3.-How-to-help-with-translations).'

      - name: Commit
        run: |
          git config --global user.name 'ThePBone'
          git config --global user.email 'thepbone@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Update translation statuses"
          git push
